#!/bin/bash
#SBATCH --job-name=sppr1
#SBATCH --output=outpsp2.log
#SBATCH --error=errorsp2.log
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=2
#SBATCH --mem=16GB
#SBATCH --time=04:00:00



# Activate the virtual environment
source ~/software/init-conda
conda activate pytorch432

# Change to the working directory
python ~/project_group/tr1/prsp2.py
# Run the training script
conda deactivate
